config/routes.rb
Rails.application.routes.draw do
	root "watches#index"
	resources :watches do
		# Get http://localhost:3000/watches/:watch_id/orders/new
		# Post <form action=" /watches/:watch_id/orders/"</form>
		resources :orders, only: [:new, :create]
	end
	resources :orders, only: :show
	resources :users, except: [:index, :show]
	resource :session
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	belongs_to :watch
	validates :stripe_token, presence: true

	def save_and_charge
		Stripe.api_key = Rails.application.secrets.stripe_secret_key

		Stripe::Charge.create(
		  :amount => amount,
		  :currency => "gbp",
		  :source => stripe_token, # obtained with Stripe.js
		  :description => "#{user.email} charged for #{watch.name}"
		)	

		self.save

	rescue Stripe::CardError => e
		body = e.json_body
		err = body[:error]
		if err[:message] == "Your card has insufficient funds" or err[:message] == "Your card was declined"
			errors.add :base, err[:message]
		else
			errors.add :base, "There was a problem charding your card. Try contacting help@timekeep.com"
		end
		false
	end

	def amount
		watch.price_in_pence 
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :watches
	has_many :orders

	validates :email, presence: true

	def owns(resource)
		self == resource.user
	end

	def full_name
		if first_name.present? and last_name.present?
			[first_name, last_name].join(" ")
		else 
			name
		end	
	end

	def name
		first_name || username || email
		if first_name.present?
				first_name
		elsif username.present?
				username
		else
				email
		end
	end


end

app/models/watch.rb
class Watch < ActiveRecord::Base
	belongs_to :user
	has_many :orders

	has_attached_file :image, :styles => { :medium => "300x300#", :thumb => "100x100>" }, :default_url => "/images/:style/missing.svg"
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	
	validates :user, presence: true
	validates :name, presence: true, uniqueness: true
	validates :description, presence: true
	validates :brand, presence: true
	validates :price_in_pence, numericality: {greater_than_or_equal_to:3999}

	def price
		price_in_pence.to_f / 100
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
  	if logged_in?
  		User.find(session[:user_id])
  	end
  end

  def logged_in?
  	session[:user_id].present?
  end

  def require_user
    unless logged_in? 
      flash[:error] = "You must be logged in to do that"
      redirect_to new_session_path
    end
  end

  def require_owner(resource)
    unless logged_in? and current_user.owns(resource)
      flash[:error] = "You must own the #{resource.class.to_s.downcase} to do that"
      redirect_to root_path
      
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :require_user, except: [:show]

  def new
  	@order = Order.new
  end

  def create
  	# Find the watch
  	@watch = Watch.find(params[:watch_id])
  	# Create a new order with watch_id = @watch.id
  	@order = @watch.orders.new(order_params)
  	# Set user_id = current_user_id
  	@order.user = current_user
  	# Charging code goes here
  	if @order.save_and_charge
  		flash[:success] = "Success"
  		redirect_to @order
  	else
  		flash[:error] = "Please check form for errors and try again"
  		render :new
  	end
	end

  def show
  	@order = Order.find(params[:id])
  	require_owner(@order) # Make sure order.user_id == curent_user.id
  end

  private
  def order_params
  	params.require(:order).permit(:stripe_token)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  	# Dont need to assign anything not saving anything to DB
  end

  def create
  	# Log in functionality goes here
  	email = params[:session][:email]
  	password = params[:session][:password]

  	@user=User.find_by(email: email)
  	if @user.present? and @user.authenticate(password)
  		# Wipe the session clean
  		reset_session
  		# Log in
  		session[:user_id] = @user.id
  		flash[:success] = "Logged in."
  		redirect_to root_path
  	else
  		flash[:error] = "Try again"
  		render :new
  	end
  end

  def show
    require_user
  end

  def destroy
  	reset_session
  	flash[:success] = "Logged out. See you again soon"
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		# Log the user in
  		# Wipe the session clean and then log new user in
  		reset_session
  		session[:user_id] = @user.id
  		flash[:success] = "Thanks for signing up"
  		redirect_to root_path
  	else
  		flash[:error] = "Please check the form for errors and try again"
  		render :new
  	end
  end

  def edit
  end

  private
  def user_params
  	params.require(:user).permit(
  		:first_name, 
  		:last_name, 
  		:password, 
  		:password_confirmation, 
  		:username,
  		:email,
  		:address_line_one,
  		:address_line_two,
  		:address_line_three,
  		:address_line_four,
  		:postcode
  		)
  end
end

app/controllers/watches_controller.rb
class WatchesController < ApplicationController
  before_action :require_user, only: [:new, :create]

  def index
  	@watches = Watch.all
  end

  def show
  	@watch = Watch.find(params[:id])
  end

  def new
    @watch = Watch.new
  end

  def create
    @watch = Watch.new(watch_params)
    @watch.user = current_user
    if @watch.save 
      flash[:success] = "Thanks for uploading a watch."
      redirect_to @watch
    else
      flash[:error] = "Please check form for errors and try again"
      render :new
    end
  end

  def edit
    @watch = Watch.find(params[:id])
    require_owner(@watch)
  end

  def update
    @watch = Watch.find(params[:id])

    if @watch.update(watch_params)
      flash[:success] = "Update #{@watch.name}"
      redirect_to @watch
    else
      flash[:error] = "Please check form for errors and try again"
      render :edit
    end 
    require_owner(@watch)
  end

  def destroy
    @watch = Watch.find(params[:id])

    flash[:success] = "'#{@watch.name}' was successfully removed" if @watch.destroy 
    redirect_to root_path
    require_owner(@watch)
  end

  private
  
  def watch_params
    params.require(:watch).permit(:name, :description, :price_in_pence, :gender, :style, :brand, :pre_owned, :image)
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/watches_helper.rb
module WatchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timekeep</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Only load it on orders new action later -->
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
</head>
<body data-stripe-publishable-key="<%= Rails.application.secrets.stripe_publishable_key %>">
<div class="container">
	<header>
		<nav>
			<%= link_to root_path do %>
				<h1>Time<br>Keep</h1>
			<% end %>
			
			<div class="actions">
				<% if logged_in? %>
					<%= link_to current_user.full_name, session_path %>
					<%= link_to "Log out", session_path, method: :delete, class: :button %>
				<% else %>
					<%= link_to "Log in", new_session_path %>
					<%= link_to "Sign up", new_user_path %>
				<% end %>
			</div>
		</nav>
		<% flash.each do |key, value| %>
			<div class="flash <%= key %>">
				<p><%= value %></p>
			</div>
		<% end %>
	</header>
	<%= yield %>
</div>
	<footer>
		<div class="container">
			<address>
				<p>Get in touch</p>
				<p>Exmouth House</p>
				<p>3-11 Pine Street</p>
			</address>
			
			<div>
				<a href="tel:+442071395252">+44 (0)20 7139 5252</a>
			</div>

			<div>
				<p><%= mail_to "hello@timekeep.com" %></p>
			</div>

			<div class="social">
				<%# social_link_to :facebook %>
				<%# social_link_to :twitter %>
			</div>
		</div>
	</footer>

	<script type="text/javascript">
		  // This identifies your website in the createToken call below
		  Stripe.setPublishableKey($('body').data('stripe-publishable-key'));
		  // ...
		jQuery(function($) {
	  	$('#new_order').submit(function(event) {
	    var $form = $(this);

	    // Disable the submit button to prevent repeated clicks
	    $form.find('button').prop('disabled', true);

	    Stripe.card.createToken($form, stripeResponseHandler);

	    // Prevent the form from submitting with the default action
	    return false;
	  	});
		});
	function stripeResponseHandler(status, response) {
 	 var $form = $('#new_order');

  	if (response.error) {
	    // Show the errors on the form
	    $form.find('.payment-errors').text(response.error.message);
	    $form.find('button').prop('disabled', false);
  	} else {
	    // response contains id and card, which contains additional card details
	    var token = response.id;
	    // Insert the token into the form so it gets submitted to the server
	    $form.append($('<input type="hidden" name="order[stripe_token]" />').val(token));
	    // and submit
	    $form.get(0).submit();
	  }
	};
	</script>

</body>
</html>

app/views/orders/new.html.erb
<%= simple_form_for @order, url: watch_orders_path do |f| %>
	<span class="payment-errors">
    <% @order.errors.full_messages.each do |error| %>
      <%= error %>
    <% end %>
  </span>

  <div class="form-row">
    <label>
      <span>Card Number</span>
     </label>
      <input type="text" size="20" data-stripe="number"/>
  </div>

  <div class="form-row">
    <label>
      <span>CVC</span>
      </label>
      <input type="text" size="4" data-stripe="cvc"/>
  </div>

  <div class="form-row">
    <label>
      <span>Expiration (MM/YYYY)</span>
    </label>
      <input type="text" size="2" data-stripe="exp-month"/>
    <span> / </span>
    <input type="text" size="4" data-stripe="exp-year"/>
  </div>

  <button type="submit">Submit Payment</button>
<% end %>

app/views/orders/show.html.erb
<section class="order__info">
	<h2> Thank You </h2>
	<h3> Order No. #<%= @order.id %></h3> 

	<p> Your account has been debited <%= number_to_currency @order.watch.price, unit: "£"%></p>
	</br>
	<p> Your <em> <%= link_to @order.watch.name, watch_path(@order.watch) %></em> will be dispatched soon </p>

	<div class="watch">
		<%= image_tag @order.watch.image.url(:medium) %>
	</div>
</section>

<section>
	<%= link_to "Need to update your delivery details?", edit_user_path %>
</section>

app/views/users/_form.html.erb

<%= simple_form_for @user do |f| %>
	<%= f.input :email %>
	<%= f.input :first_name %>
	<%= f.input :last_name %>
	<%= f.input :username %>
	<%= f.input :password %>
	<%= f.input :password_confirmation %>
	
	<%= f.input :address_line_one %>	
	<%= f.input :address_line_two %>	
	<%= f.input :address_line_three %>
	<%= f.input :address_line_four %>
	<%= f.input :postcode %>

	<%= f.button :submit, "Sign Up" %>
<% end %>

app/views/users/edit.html.erb
<%= render "form" %>

app/views/users/new.html.erb
<%= render "form" %>

app/views/watches/_form.html.erb

<%= simple_form_for @watch do |f| %>
	<%= f.input :name %>
	<%= f.input :description %>
	<%= f.input :price_in_pence %>
	<%= f.input :style %>
	<%= f.input :gender %>
	<%= f.input :brand %>
	<%= f.input :pre_owned %>
	<%= f.input :image, as: :file %>
	<%= f.button :submit, "Upload Watch" %>
<% end %>

app/views/watches/index.html.erb
<section class="watches">
	<% @watches.each do |watch| %>
			<div class="watch">
			
			<!-- Add in link to showpage -->
			<%= link_to watch_path(watch) do %>
				
				<!-- Add in image here -->
				<%= image_tag watch.image.url(:medium) %>

				<div class="price">
					<!-- link this to new_orders -->
				<span>
						<%= link_to(number_to_currency(watch.price, unit: "£"), new_watch_order_path(watch)) %>
				</span>
				
				</div>
					<h2><%= watch.name %></h2>
				</div>
		<% end %>
	<% end %>
</section>

app/views/watches/show.html.erb
<section class="watch__large">
	<!-- include large image here -->
	<%= image_tag @watch.image.url(:medium) %>
</section>

<section class="watch__info">
	<h2><%= @watch.name %></h2>
	<%= simple_format @watch.description %>
	<div>
		<span>Posted by <%= mail_to @watch.user.email, @watch.user.name %></span>
	</div>
	<div class="actions">
		<% if logged_in? and current_user.owns(@watch) %>
			<%= link_to "Edit", edit_watch_path(@watch) %>
			<%= link_to "Delete", watch_path(@watch), method: :delete, class: "button", data: {confirm: "Are you sure?"} %>
		<% else %>
			<b><%= number_to_currency @watch.price, unit: "£" %></b>
			<%= link_to "Buy", new_watch_order_path(@watch)	 %>
		<% end %>
	</div>
</section>